export const AST_TYPES = {
  LogicalExpression: "LogicalExpression",
  BinaryExpression: "BinaryExpression",
  UnaryExpression: "UnaryExpression",
  UpdateExpression: "UpdateExpression",
  CallExpression: "CallExpression",
  MemberExpression: "MemberExpression",
  Identifier: "Identifier",
  Literal: "Literal",
  TemplateLiteral: "TemplateLiteral",
  VariableDeclarator: "VariableDeclarator",
  ReturnStatement: "ReturnStatement",
  TSUnionType: "TSUnionType",
  TSLiteralType: "TSLiteralType",
  TSTypeReference: "TSTypeReference",
  TSStringKeyword: "TSStringKeyword",
  TSNumberKeyword: "TSNumberKeyword",
  TSBooleanKeyword: "TSBooleanKeyword",
  TSNullKeyword: "TSNullKeyword",
  TSUndefinedKeyword: "TSUndefinedKeyword",
  TSVoidKeyword: "TSVoidKeyword",
  TSAnyKeyword: "TSAnyKeyword",
  TSUnknownKeyword: "TSUnknownKeyword",
  TSNeverKeyword: "TSNeverKeyword",
} as const;
